### ISSUE TITLE
Crashes upon picking file

### ISSUE THREAD

**Issue by PacoBell** [psanford/wormhole-william-mobile#19]
I'm running the app in Graphene OS (Android 12). The app opens fine, but crashes immediately when I try to choose a file. It also didn't request any permissions, not that it matters. It still crashes the same even if I give it all the permissions available. Any way I could debug this further?

**Comment by psanford** [comment]
Can you run `logcat` on the process and then trigger the crash?
```
$ adb shell pidof io.sanford.wormhole_william
2859
$ adb logcat --pid=2859
```

**Comment by psanford** [comment]
@PacoBell are you able to get any logs from the app?

**Comment by uyar** [comment]
I'm not sure whether this is what you want or not, but here is what I've come up with:

``
--------- beginning of main
02-22 23:20:49.688 20147 20171 D OpenGLRenderer: HWUI GL Pipeline
02-22 23:20:49.697 20147     0 E Go      : panic: runtime error: index out of range [0] with length 0
02-22 23:20:49.697 20147     0 E Go      : 
02-22 23:20:49.697 20147     0 E Go      : goroutine 35 [running, locked to thread]:
02-22 23:20:49.697 20147 20165 I io.sanford.wormhole_william: panic: runtime error: index out of range [0] with length 0
02-22 23:20:49.697 20147     0 E Go      : gioui.org/io/router.(*pointerQueue).appendSemanticChildren(0x4000048e88?, {0x0?, 0x4000002680?, 0x4000048be0?}, 0x7?)
02-22 23:20:49.697 20147 20165 I io.sanford.wormhole_william: 
02-22 23:20:49.697 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/io/router/pointer.go:373 +0x2c8
02-22 23:20:49.698 20147     0 E Go      : gioui.org/io/router.(*pointerQueue).AppendSemantics(0x4?, {0x0, 0x0, 0x0})
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/io/router/pointer.go:349 +0x48
02-22 23:20:49.698 20147     0 E Go      : gioui.org/io/router.(*Router).AppendSemantics(...)
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/io/router/router.go:186
02-22 23:20:49.698 20147     0 E Go      : gioui.org/app.(*Window).updateSemantics(0x4000194000)
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:619 +0xac
02-22 23:20:49.698 20147     0 E Go      : gioui.org/app.(*Window).lookupSemantic(...)
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:606
02-22 23:20:49.698 20147     0 E Go      : gioui.org/app.(*Window).run(0x4000194000, {0x400018c000, 0x3, 0x4})
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:701 +0x914
02-22 23:20:49.698 20147     0 E Go      : created by gioui.org/app.NewWindow
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:169 +0x620
--------- beginning of crash
02-22 23:20:49.698 20147 20164 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 20164 (ormhole_william)
``
